name: Publish Docker Alpine
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths: ['runtimes/**','.github/workflows/build-alpine.yml']
  schedule:
    - cron: 0 0 * * 3
jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            php: [8.1,8.2,8.3,8.4,8.5]
            node: [20,22,24]
            exclude:
              - php: 8.4
                node: 20
              - php: 8.5
                node: 20
              - php: 8.5
                node: 22
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          context: ./runtimes/common
          file: ./runtimes/${{ matrix.php }}/DockerfileAlpine
          push: true
          build-args: NODE_VERSION=${{ matrix.node }}
          tags: |
           ariaieboy/sail-runtime-image:${{ matrix.php }}-${{ matrix.node }}-alpine
           ${{ (matrix.node == 20) && format('ariaieboy/sail-runtime-image:{0}-alpine',matrix.php) || null }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
